-- ShopBot Database Schema
-- Run this script in the Supabase SQL Editor or locally using setup-db.js

-- Drop existing tables if they exist in reverse dependency order
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;

-- 1. Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  stock_quantity NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  reorder_level NUMERIC(10, 2) NOT NULL DEFAULT 10 CHECK (reorder_level >= 0),
  unit TEXT NOT NULL DEFAULT 'piece',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Customers Table
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create an index on phone for O(1) customer lookups
CREATE INDEX idx_customers_phone ON customers(phone);

-- 3. Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_phone TEXT NOT NULL REFERENCES customers(phone) ON DELETE CASCADE,
  total_amount NUMERIC(10, 2) NOT NULL CHECK (total_amount >= 0),
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Order Items Table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity NUMERIC(10, 2) NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed Default High-Quality Grocery Products
INSERT INTO products (name, price, stock_quantity, reorder_level, unit) VALUES
('atta', 45.00, 100.00, 20.00, 'kg'),
('oil', 150.00, 50.00, 10.00, 'litre'),
('milk', 60.00, 40.00, 10.00, 'litre'),
('sugar', 40.00, 80.00, 15.00, 'kg'),
('potato', 25.00, 150.00, 30.00, 'kg'),
('daal', 120.00, 60.00, 12.00, 'kg'),
('bread', 40.00, 30.00, 8.00, 'piece');

-- Seed Mock Customer for Webhook Testing
INSERT INTO customers (phone, name) VALUES
('919876543210', 'Yuvraj');

-- 5. Chat Sessions Table (for Conversational AI Memory)
CREATE TABLE IF NOT EXISTS chat_sessions (
  customer_phone TEXT PRIMARY KEY REFERENCES customers(phone) ON DELETE CASCADE,
  history JSONB NOT NULL DEFAULT '[]',
  cart JSONB NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
